$(document).ready(function(){
    $(".capa").hide();
	$("#livro1").mouseenter(function(){
		$("#capa1").show(100);
	});
	$("#livro1").mouseleave(function(){
		$("#capa1").hide(100);
	});
	$("#livro2").mouseenter(function(){
		$("#capa2").show(100);
	});
	$("#livro2").mouseleave(function(){
		$("#capa2").hide(100);
	});
	$("#livro3").mouseenter(function(){
		$("#capa3").show(100);
	});
	$("#livro3").mouseleave(function(){
		$("#capa3").hide(100);
	});
	$("#livro4").mouseenter(function(){
		$("#capa4").show(100);
	});
	$("#livro4").mouseleave(function(){
		$("#capa4").hide(100);
	});
	$("#livro5").mouseenter(function(){
		$("#capa5").show(100);
	});
	$("#livro5").mouseleave(function(){
		$("#capa5").hide(100);
	});
	$("#livro6").mouseenter(function(){
		$("#capa6").show(100);
	});
	$("#livro6").mouseleave(function(){
		$("#capa6").hide(100);	
	});
	$("#livro7").mouseenter(function(){
		$("#capa7").show(100);
	});
	$("#livro7").mouseleave(function(){
		$("#capa7").hide(100);		
	});
	$("#livro8").mouseenter(function(){
		$("#capa8").show(100);
	});
	$("#livro8").mouseleave(function(){
		$("#capa8").hide(100);
	});
});